### PR TITLE
ongoing josh PR

### PR DESCRIPTION
**Pull request by joshfttb**

### CODE REVIEW

**Comment by JustinLivi** [comment]
@joshfttb are you able to resolve the conflicts? This is looking really good and I'd like to able to merge in

**Comment by joshfttb** [comment]
@JustinLivi I'll make the path changes we discussed today and then resolve

**Comment by joshfttb** [comment]
@JustinLivi - there you go. conflicts are resolved

**Comment by BrianSilvia** [comment]
I'll merge this in, once my PR is merged in.

**Comment by joshfttb** [comment]
ready for final pull

**Comment by JustinLivi** [comment]
Merged with most recent push

**Pull request closed without merging**
